# Site Settings
title:               The Waffle Stack
tagline:             Friends, Food, and Work
description:
baseurl:            "/blog"
url:                "http://jondailey.me/blog"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Jonathan Dailey"
  email:             "jd@jondailey.me"
  twitter:           "jondailey"
  instagram:         "ruggedtravels"
  github:            "jdailey12"
  # facebook:          "Le.Paul.94"
  # linkedin:          "lenpaul"
navigation:
- title: About
  url: /about
# - title: Writing
#   url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
